//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultorioMMPI.DataBase
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Clientes
    {
        [Required(ErrorMessage = "El número preventivo es obligatorio.")]
        [DataType(DataType.Text)]
        public string NumPreventivo { get; set; }
        [Required(ErrorMessage = "La fecha de nacimiento es obligatoria.")]
        [DataType(DataType.DateTime)]
        public System.DateTime FechaNacimiento { get; set; }
        [Required(ErrorMessage = "El sexo es obligatorio.")]
        public int Sexo { get; set; }
        [Required(ErrorMessage = "La escolaridad es obligatoria.")]
        [DataType(DataType.Text)]
        public string Escolaridad { get; set; }
        [Required(ErrorMessage = "La fecha de registro es obligatoria.")]
        [DataType(DataType.DateTime)]
        public System.DateTime FechaRegistro { get; set; }
        [Required(ErrorMessage = "El telefono es obligatorio.")]
        [DataType(DataType.PhoneNumber)]
        public string Telefono { get; set; }
        [Required(ErrorMessage = "El nombre es obligatorio.")]
        [DataType(DataType.Text)]
        public string Nombre { get; set; }
        [Required(ErrorMessage = "La edad es obligatoria.")]
        public int Edad { get; set; }
        [Required(ErrorMessage = "El estado civil es obligatorio")]
        public string EstadoCivil { get; set; }
        [Required(ErrorMessage = "La ocupación es obligatoria.")]
        public string Ocupacion { get; set; }
        [Required(ErrorMessage = "El lugar de residencia es obligatorio.")]
        [DataType(DataType.Text)]
        public string LugarResidencia { get; set; }
        public string Resultados { get; set; }
    }
}
