//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultorioMMPI.DataBase
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UsuarioAcceso
    {
        public int id { get; set; }
        [Required(ErrorMessage = "Ingresar el usuario")]
        [DataType(DataType.Text)]
        [StringLength(25, ErrorMessage = "El usuario no debe ser mayor a 25 caractertes")]
        public string usuario { get; set; }
        [Required(ErrorMessage = "Ingresar una contraseña")]
        [DataType(DataType.Password)]
        [StringLength(25, ErrorMessage = "El contraseña no debe ser mayor a 25 caractertes")]
        public string contrasena { get; set; }
    }
}
